### ISSUE TITLE
Creating new user

### ISSUE THREAD

**Issue by maxmillan29** [GICHD/MARS-Instructions#10]
When i create new user in my organization i got error message

![image](https://user-images.githubusercontent.com/45266816/67635542-d90a7680-f8c8-11e9-87f8-1a0c0c334a48.png)

**Comment by smukahhal** [comment]
Still not fixed yet.

**Comment by smukahhal** [comment]
Ticket was opened under GICHD - MARSGICHDMARS-144 
Will report back once it is fixed.

**Comment by smukahhal** [comment]
Fixed
