### ISSUE TITLE
Error downloading Gazetteer File from MARS to Tablet 

### ISSUE THREAD

**Issue by mashrafsafi** [GICHD/MARS-Instructions#13]
I created a new file of Gazetteer as below:

> I download the current Gazetteer from **MARS System**

> I update the Village name with IMSMA location Name and GUIDs.

> I upload the updated files to the IMSMA organization.

> I Used this Gazetteer file in **DMAC MRE with Location Form.**

> But it is not downloading to my Tablet.
[1567518333-ORG-11-IMSMA-GAZETTEER.zip](https://github.com/GICHD/MARS-Instructions/files/3814260/1567518333-ORG-11-IMSMA-GAZETTEER.zip)

**Comment by smukahhal** [comment]
I will check it and get back to you.
