### ISSUE TITLE
MARS worked with new MARS app from Sluiman but issue while import data to IMSMA.

### ISSUE THREAD

**Issue by mashrafsafi** [GICHD/MARS-Instructions#15]
[Issue in MAxml while importing from MARS to IMSMA.txt](https://github.com/GICHD/MARS-Instructions/files/4069414/Issue.in.MAxml.while.importing.from.MARS.to.IMSMA.txt)

**Comment by smukahhal** [comment]
There was a missing value in the ordnance quantity that IMSMAng does it accept as null. We are working already to fix, it should be fixed this week.
