### ISSUE TITLE
Issue with Using Places in MRE

### ISSUE THREAD

**Issue by mashrafsafi** [GICHD/MARS-Instructions#5]
The issue with Places in MRE Template while exporting the MRE MARS field report. We need to overcome this issue.

**Comment by smukahhal** [comment]
Apperently this could be a bug, I have submitted it as a bug under ID - `GICHD - MARS /  Task GICHDMARS-136`
Will keep you posted once it is fixed

**Comment by smukahhal** [comment]
Issues fixed
